#!/bin/bash
set -e

psql --username postgres  <<-EOSQL
   CREATE ROLE ${REPLICATION_USER} ENCRYPTED PASSWORD '${REPLICATION_PASSWORD}' REPLICATION LOGIN;
EOSQL

psql --username postgres <<-EOSQL
   CREATE DATABASE ${DATABASE};
   CREATE ROLE ${PROJECT_USER} ENCRYPTED PASSWORD '${PROJECT_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
   GRANT ALL PRIVILEGES ON DATABASE ${DATABASE} to ${PROJECT_USER};
EOSQL
